# @name register
POST {{API_URL}}/users
Content-Type: application/json

{
    "name":"{{name}}",
    "email":"{{email}}",
    "password":"{{password}}"
}

###

# @name login
POST {{API_URL}}/login 
Content-Type: application/json

{
    "email":"{{email}}",
    "password":"{{password}}"
}

###

@authToken ={{login.response.body.token}}

# @name me
GET   {{API_URL}}/users/me
Authorization: Bearer {{authToken}}

###

# @name users
GET   {{API_URL}}/users
Authorization: Bearer {{authToken}}


###

# @name getHabits
Get {{API_URL}}/habits 
Authorization: Bearer {{authToken}}

###

# @name postHabit
POST {{API_URL}}/habits 
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "OwnerId": 1,
    "Name": "testuser",
    "Description": "test habit",
    "Reward": "test reward",
    "Favorite": true,
    "PublicHabit": true
}
###
